/storage/emulated/0/Download/gitlab-foss-Cherry.tar
Cannot create symbolic link /storage/emulated/0/Download/Download/gitlab-foss-Cherry/gitlab-foss-Cherry/vendor/gitignore/Clojure.gitignore
• Operation not permitted
... some similar messages are skipped
Cannot create symbolic link /storage/emulated/0/Download/Download/gitlab-foss-Cherry/gitlab-foss-Cherry/vendor/gitignore/Kotlin.gitignore
• Operation not permitted

/storage/emulated/0/Download/.com.google.Chrome.8wLWpV
Bad or unknown format /storage/emulated/0/Download/.com.google.Chrome.8wLWpV archive

/storage/emulated/0/Download/.com.google.Chrome.E4mnmJ
Bad or unknown format /storage/emulated/0/Download/.com.google.Chrome.E4mnmJ archive

/storage/emulated/0/Download/.com.google.Chrome.kk23e9
Bad or unknown format /storage/emulated/0/Download/.com.google.Chrome.kk23e9 archive

/storage/emulated/0/Download/.com.google.Chrome.vtLQBN
Bad or unknown format /storage/emulated/0/Download/.com.google.Chrome.vtLQBN archive

/storage/emulated/0/Download/.com.google.Chrome.xDfXnr
Bad or unknown format /storage/emulated/0/Download/.com.google.Chrome.xDfXnr archive

/storage/emulated/0/Download/.com.google.Chrome.XgGRZ4
Bad or unknown format /storage/emulated/0/Download/.com.google.Chrome.XgGRZ4 archive

/storage/emulated/0/Download/A.clazz
Bad or unknown format /storage/emulated/0/Download/A.clazz archive

/storage/emulated/0/Download/angular-master (1).zip.crdownload
Corrupt archive /storage/emulated/0/Download/angular-master (1).zip.crdownload

/storage/emulated/0/Download/angular-master.zip.crdownload
Corrupt archive /storage/emulated/0/Download/angular-master.zip.crdownload

/storage/emulated/0/Download/app_src_main_res_mipmap-hdpi_ic_launcher.png
Bad or unknown format /storage/emulated/0/Download/app_src_main_res_mipmap-hdpi_ic_launcher.png archive

/storage/emulated/0/Download/app_src_main_res_mipmap-ldpi_ic_launcher.png
Bad or unknown format /storage/emulated/0/Download/app_src_main_res_mipmap-ldpi_ic_launcher.png archive

/storage/emulated/0/Download/app_src_main_res_mipmap-mdpi_ic_launcher.png
Bad or unknown format /storage/emulated/0/Download/app_src_main_res_mipmap-mdpi_ic_launcher.png archive

/storage/emulated/0/Download/Azure Fundamentals Learning Path (July 2019).pdf
Bad or unknown format /storage/emulated/0/Download/Azure Fundamentals Learning Path (July 2019).pdf archive

/storage/emulated/0/Download/book.pdf
Bad or unknown format /storage/emulated/0/Download/book.pdf archive

/storage/emulated/0/Download/bugs-2019-10-02.csv
Bad or unknown format /storage/emulated/0/Download/bugs-2019-10-02.csv archive

/storage/emulated/0/Download/buildroot-2019.02.5.tar.gz.sign
Bad or unknown format /storage/emulated/0/Download/buildroot-2019.02.5.tar.gz.sign archive

/storage/emulated/0/Download/BuildStream-1.2.0.news
Bad or unknown format /storage/emulated/0/Download/BuildStream-1.2.0.news archive

/storage/emulated/0/Download/BuildStream-1.2.0.news.meta4
Bad or unknown format /storage/emulated/0/Download/BuildStream-1.2.0.news.meta4 archive

/storage/emulated/0/Download/BuildStream-1.2.0.news.metalink
Bad or unknown format /storage/emulated/0/Download/BuildStream-1.2.0.news.metalink archive

/storage/emulated/0/Download/BuildStream-1.3.1.news
Bad or unknown format /storage/emulated/0/Download/BuildStream-1.3.1.news archive

/storage/emulated/0/Download/BuildStream-1.3.1.news.meta4
Bad or unknown format /storage/emulated/0/Download/BuildStream-1.3.1.news.meta4 archive

/storage/emulated/0/Download/BuildStream-1.3.1.news.metalink
Bad or unknown format /storage/emulated/0/Download/BuildStream-1.3.1.news.metalink archive

/storage/emulated/0/Download/BuildStream-1.4.0.news
Bad or unknown format /storage/emulated/0/Download/BuildStream-1.4.0.news archive

/storage/emulated/0/Download/ccr2019-report.pdf
Bad or unknown format /storage/emulated/0/Download/ccr2019-report.pdf archive

/storage/emulated/0/Download/ChicagoFLF.ttf
Bad or unknown format /storage/emulated/0/Download/ChicagoFLF.ttf archive

/storage/emulated/0/Download/Cluster.clazz
Bad or unknown format /storage/emulated/0/Download/Cluster.clazz archive

/storage/emulated/0/Download/cmpdir.exe
Bad or unknown format /storage/emulated/0/Download/cmpdir.exe archive

/storage/emulated/0/Download/crosby.pdf
Bad or unknown format /storage/emulated/0/Download/crosby.pdf archive

/storage/emulated/0/Download/DataClass.clazz
Bad or unknown format /storage/emulated/0/Download/DataClass.clazz archive

/storage/emulated/0/Download/DS_Store
Bad or unknown format /storage/emulated/0/Download/DS_Store archive

/storage/emulated/0/Download/DS_Store (1)
Bad or unknown format /storage/emulated/0/Download/DS_Store (1) archive

Too many messages
